### PR TITLE
fix: serialise breadcrumb level as string instead of integer

### LINKED ISSUE #289: Breadcrumbs: Breadcrumb level is sent as number instead of an enum string
**Describe the bug**
It seems RG4Flutter sends numeric values for the level field in breadcrumbs instead of enum values.

That can then lead to model binding issues on the RG backend.

**Expected behavior**
Use `info`, `debug`, `warning` or `error` for the level

### PR DESCRIPTION
**Pull request by TheRealAgentK**
### Description :memo:
- **Purpose**: Fixes #289 — `RaygunBreadcrumbLevel` was serialised as integers (0–3) instead of strings (`debug`, `info`, `warning`, `error`), causing model binding issues on the Raygun backend.
- **Approach**: Changed `@JsonValue` annotations on the `RaygunBreadcrumbLevel` enum from integer values to string values, matching the [Raygun API spec](https://raygun.com/documentation/product-guides/crash-reporting/api/) and the Raygun4JS reference implementation. Regenerated `.g.dart` files.

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)

**Updates**

:point_right: Changed `@JsonValue(0)` → `@JsonValue('debug')`, `@JsonValue(1)` → `@JsonValue('info')`, etc. in `RaygunBreadcrumbLevel`
:point_right: Regenerated `raygun_breadcrumb_message.g.dart`
:point_right: Added test asserting breadcrumb levels are serialised as strings in the JSON payload
:point_right: Added `AGENTS.md` for AI coding agent guidance

### Test plan :test_tube:
- Run `flutter test` — all 15 tests pass
- New test `'Breadcrumb level is serialised as string'` asserts all four levels (`debug`, `info`, `warning`, `error`) are sent as strings

### Author to check :eyeglasses:
- [x] Project and all contained modules builds successfully
- [x] Self-/dev-tested
- [x] Unit/UI/Automation/Integration tests provided where applicable
- [x] Code is written to standards
- [x] Appropriate documentation written (code comments, internal docs)

### CODE REVIEW

**Comment by miquelbeltran** [comment]
FYI, the Android Raygun implementation also uses ints for the Breadcrumb level: https://github.com/MindscapeHQ/raygun4android/blob/342b3f6237445c8c5169787f8a0a32bc0f28c976/provider/src/main/java/com/raygun/raygun4android/messages/crashreporting/RaygunBreadcrumbMessage.kt#L9C42-L9C48

File: lib/src/messages/raygun_breadcrumb_message.dart [hunk 1]
```diff
@@ -43,12 +43,12 @@ class RaygunBreadcrumbMessage {
...
-  @JsonValue(1)
+  @JsonValue('info')
   info,
-  @JsonValue(2)
+  @JsonValue('warning')
   warning,
-  @JsonValue(3)
+  @JsonValue('error')
   error,
 }
```
Comment (miquelbeltran) [inline lib/src/messages/raygun_breadcrumb_message.dart]: You can use https://pub.dev/documentation/json_annotation/4.10.0/json_annotation/JsonEnum-class.html instead of annotating every value.

File: AGENTS.md [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+### JSON serialisation (important)
+
+All message models use **`json_annotation`** + **`json_serializable`** with code generation.
+
+- Model files live in `lib/src/messages/` and have a corresponding `.g.dart` file.
+- **Never hand-edit `.g.dart` files.** After changing any model or `@JsonValue`/`@JsonKey` annotation, regenerate with:
+  ```
+  dart run build_runner build --delete-conflicting-outputs
+  ```
+- Enum values sent to the API **must be strings**, not integers. Use `@JsonValue('stringValue')` on enum members, not numeric indices.
```
Comment (miquelbeltran) [inline AGENTS.md]: Rather than this, it should use https://pub.dev/documentation/json_annotation/4.10.0/json_annotation/JsonEnum-class.html


```suggestion
- Enum values sent to the API **must be strings**, not integers. Use `@JsonEnum` to annotate the enum class.
```

File: AGENTS.md [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+- The `.g.dart` files **must** be committed — they are not gitignored.
+- Verify serialisation matches the [Raygun API spec](https://raygun.com/documentation/product-guides/crash-reporting/api/) and the Raygun4JS reference implementation.
+
+### Versioning
+
+The version appears in **two places** that must be kept in sync:
+
+1. `pubspec.yaml` → `version:`
+2. `lib/src/services/settings.dart` → `Settings.kVersion`
+
```
Comment (miquelbeltran) [inline AGENTS.md:52]: I think we should add this to the `RELEASING.md` and then reference the file here.

File: AGENTS.md [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+- Branch off `develop` (not `master`).
+- PR titles must follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) (enforced by CI).
+- PR descriptions **must** follow the template in `pull_request_template.md`. Read it before creating a PR and fill in all sections.
+- Release branches are named `release/x.y.z`.
+- PRs merge into `develop`; `develop` is periodically merged to `master`.
+
+### CI
+
+- PR workflow validates the PR title follows Conventional Commits.
+- No automated test runner in CI currently — run `flutter test` locally before submitting.
```
Comment (miquelbeltran) [inline AGENTS.md]: This is not correct: https://github.com/MindscapeHQ/raygun4flutter/blob/develop/.github/workflows/main.yml

**Review by miquelbeltran — CHANGES_REQUESTED** [review]
Using `JsonEnum` annotation is just a suggestion, but the Agents md file constains wrong information

File: lib/src/messages/raygun_breadcrumb_message.dart (hunk 1 above)
Comment (TheRealAgentK) [reply lib/src/messages/raygun_breadcrumb_message.dart]: Yup, good point. Fixed.

File: AGENTS.md (hunk 2 above)
Comment (TheRealAgentK) [reply AGENTS.md]: Done

File: AGENTS.md (hunk 3 above)
Comment (TheRealAgentK) [reply AGENTS.md:52]: yup,  also good point. Fixed.

File: AGENTS.md (hunk 4 above)
Comment (TheRealAgentK) [reply AGENTS.md]: Fixed

**Review by miquelbeltran — APPROVED** [review]
Thank you!
